/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const OrderItem = IDL.Record({
  'qty' : IDL.Nat,
  'menuId' : IDL.Nat,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'price' : IDL.Float64,
});
export const MenuItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageEmoji' : IDL.Text,
  'isVeg' : IDL.Bool,
  'price' : IDL.Float64,
  'foodType' : IDL.Text,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'paymentStatus' : IDL.Text,
  'time' : IDL.Text,
  'tableNumber' : IDL.Nat,
  'items' : IDL.Vec(OrderItem),
});

export const idlService = IDL.Service({
  'addItemsToOrder' : IDL.Func([IDL.Nat, IDL.Vec(OrderItem)], [IDL.Bool], []),
  'addMenuItem' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text, IDL.Bool, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createOrder' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Vec(OrderItem)],
      [IDL.Nat],
      [],
    ),
  'deleteMenuItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'markAllServed' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'updateMenuItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, IDL.Text, IDL.Bool, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateOrderItemStatus' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updatePaymentStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const OrderItem = IDL.Record({
    'qty' : IDL.Nat,
    'menuId' : IDL.Nat,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'price' : IDL.Float64,
  });
  const MenuItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageEmoji' : IDL.Text,
    'isVeg' : IDL.Bool,
    'price' : IDL.Float64,
    'foodType' : IDL.Text,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'paymentStatus' : IDL.Text,
    'time' : IDL.Text,
    'tableNumber' : IDL.Nat,
    'items' : IDL.Vec(OrderItem),
  });
  
  return IDL.Service({
    'addItemsToOrder' : IDL.Func([IDL.Nat, IDL.Vec(OrderItem)], [IDL.Bool], []),
    'addMenuItem' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text, IDL.Bool, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createOrder' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Vec(OrderItem)],
        [IDL.Nat],
        [],
      ),
    'deleteMenuItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'markAllServed' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'updateMenuItem' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Bool,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Bool],
        [],
      ),
    'updateOrderItemStatus' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updatePaymentStatus' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };