/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface MenuItem {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'imageEmoji' : string,
  'isVeg' : boolean,
  'price' : number,
  'foodType' : string,
}
export interface Order {
  'id' : bigint,
  'paymentStatus' : string,
  'time' : string,
  'tableNumber' : bigint,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'qty' : bigint,
  'menuId' : bigint,
  'status' : string,
  'name' : string,
  'price' : number,
}
export interface _SERVICE {
  'addItemsToOrder' : ActorMethod<[bigint, Array<OrderItem>], boolean>,
  'addMenuItem' : ActorMethod<
    [string, number, string, boolean, string, string],
    bigint
  >,
  'createOrder' : ActorMethod<[bigint, string, Array<OrderItem>], bigint>,
  'deleteMenuItem' : ActorMethod<[bigint], boolean>,
  'getMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'markAllServed' : ActorMethod<[bigint], boolean>,
  'updateMenuItem' : ActorMethod<
    [bigint, string, number, string, boolean, string, string],
    boolean
  >,
  'updateOrderItemStatus' : ActorMethod<[bigint, bigint, string], boolean>,
  'updatePaymentStatus' : ActorMethod<[bigint, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];